### ISSUE TITLE
Add steepness to graphs

### ISSUE THREAD

**Issue by danionita** [danionita/e3fraud#8]
In graphs, additional explanation regarding the gradient (steepness) of a particular (straight) line

**Comment by larswolos** [comment]
What is meant is some additional explanation regarding the gradient (steepness) of a particular (straight) line, i.e. anything helping the user to better understand the computations behind each line. This explanation could be displayed wherever helpful: Ideally there would be either some sort of mouse-over effect with an explanation popping up for each line, or a separate box below the graph which looks like a legend of symbols, but shows every coloured line in use with some additional info. Or even both, mouse-over and a box.

**Comment by danionita** [comment]
Added slope and average in the legend
